apiVersion: batch/v1
kind: Job
metadata:
  name: cifar-10-10-180-local
spec:
  template:
    spec:
      automountServiceAccountToken: false
      containers:
      - name: gpu-container
        image: gitlab-registry.nrp-nautilus.io/prp/jupyter-stack/prp:latest
        resources:
          limits:
            memory: 10Gi
            cpu : "10"
            nvidia.com/gpu: "3"
          requests:
            memory: 10Gi
            cpu : "10"
            nvidia.com/gpu: "3"
        volumeMounts:
          - mountPath: /base_vol
            name: base-vol
        command: ["/bin/bash", "-c"]
        args:
          - cd /base_vol/sr_fca_main/;
            /bin/bash install_ffcv.sh
      restartPolicy: Never
      volumes:
        - name: base-vol
          persistentVolumeClaim:
            claimName: base-vol
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: topology.kubernetes.io/region
                operator: In
                values:
                - us-west