
model: 
  name: stacked_lstm
  params:
    seq_len : 80
    emb_dim: 8
    n_hidden: 100
    num_classes : 80
    n_layers: 2
freq:
  metrics: 5
  save: 150
  print: 100
num_clients_per_round: 3
local_iter: 5
rounds: 2
num_clusters : 3
optimizer:
  name: sgd
  params:
    lr: 0.003
    momentum: 0.9

