model: 
  name: two_layer_lin
  params:
    input_size: 784
    hidden_size: 200
    num_classes: 10

num_clusters : 2
freq:
  metrics: 5
  save: 150
  print: 100
num_clients_per_round: 3
local_iter: 5
rounds: 60
optimizer:
  name: sgd
  params:
    lr: 0.1