batch:
  test: 512
  train: 50
clustering: fedavg
dataset:
  dimension: 1000
  name: synthetic
  noise_scale: 0.001
  num_clusters: 2
  num_samples:
    test: 100
    train: 100
  scale: 1
freq:
  metrics: 30
  print: 30
  save: 60
iterations: 20
local_iter: 2
model:
  name: one_layer_lin
  params:
    dimension: 1000
    scale: 1
num_clients: 50
num_clients_per_round: 9
optimizer:
  name: sgd
  params:
    lr: 0.0012818957761503438
    momentum: 0.6790195688922952
optimizer_name: sgd
optimizer_params_lr: 0.0012818957761503438
optimizer_params_momentum: 0.6790195688922952
path:
  data: /base_vol/sr_fca_main/experiments/synthetic/seed_9/data
  results: /base_vol/sr_fca_main/experiments/synthetic/seed_9/results/fedavg
rounds: 10
seed: 9
time:
  t0: 1665332478.1341777
  tcluster: 1665332492.3793583
  tdataset: 1665332479.4634507
  tnew: 1665332479.4634507
