model: 
  name: one_layer_lin
rounds : 60
local_iter: 5
freq:
  metrics: 5
  save: 150
  print: 100
num_clients_per_round: 3
optimizer:
  name: sgd
  params:
    lr: 0.1

# {
#     "m" : 100,
#     "p" : 2,

#     "n" : 100,
#     "d" : 1000,

#     "r" : 1.0,

#     "noise_scale": 0.001,

#     "num_epochs": 300,
#     "score":"set",
#     "lr":0.1,
#     "data_seed":0,
#     "train_seed":0
# }
