model: 
  name: one_layer_lin
dist_fraction: 0.5
size_threshold: 2
freq:
  metrics: 5
  save: 150
  print: 100
num_refine_steps: 2
beta: 0.2
num_clients_per_round: 7
init:
  iterations: 20
refine:
  local_iter: 5
  rounds: 4
optimizer:
  name: sgd
  params:
    lr: 0.01
dist_metric : euclidean