model: 
  name: one_layer_lin
dist_threshold: 0.5
size_threshold: 1
freq:
  metrics: 5
  save: 150
  print: 100
num_refine_steps: 2
beta: 0.15
num_clients_per_round: 3
init:
  iterations: 300
refine:
  local_iter: 5
  rounds: 60
optimizer:
  name: sgd
  params:
    lr: 0.1