client_threshold: 0.19402007658547657
freq:
  metrics: 30
  print: 60
  save: 150
gamma_max: 0.5310690092746259
iterations: 1000
local_iter: 5
model:
  name: simplecnn
num_clients_per_round: 10
num_clusters: 2
optimizer:
  name: sgd
  params:
    lr: 0.04
rounds: 200
stop_threshold: 0.029658690479226833
