model: 
  name: two_layer_lin
  params:
    input_size: 784
    hidden_size: 200
    num_classes: 10    
freq:
  metrics: 5
  save: 150
  print: 5
num_clients_per_round: 10
local_iter: 5
rounds: 2
iterations: 10
optimizer:
  name: adam
  params:
    lr: 0.0002
num_clusters: 2
