freq:
  metrics: 30
  print: 60
  save: 150
iterations: 250
local_iter: 5
model:
  name: two_layer_lin
  params:
    hidden_size: 200
    input_size: 784
    num_classes: 10
num_clients_per_round: 10
optimizer:
  name: adam
  params:
    lr: 0.000743656035585964
optimizer_name: adam
optimizer_params_lr: 0.000743656035585964
rounds: 50
