client_threshold: 4.538159432170397
freq:
  metrics: 30
  print: 100
  save: 150
gamma_max: 0.5550000069704653
iterations: 280
local_iter: 5
model:
  name: two_layer_lin
  params:
    hidden_size: 200
    input_size: 784
    num_classes: 10
num_clients_per_round: 10
num_clusters: 2
optimizer:
  name: adam
  params:
    lr: 0.0002
rounds: 56
stop_threshold: 0.027737997303235704
