batch:
  test: 512
  train: 50
client_threshold: 10.544845630752837
clustering: cfl
dataset:
  hidden_size: 200
  input_size: 784
  name: inv_mnist
  num_classes: 10
  num_clusters: 2
freq:
  metrics: 30
  print: 100
  save: 150
gamma_max: 0.8396149754758221
iterations: 210
local_iter: 4
model:
  name: two_layer_lin
  params:
    hidden_size: 200
    input_size: 784
    num_classes: 10
num_clients: 100
num_clients_per_round: 4
num_clusters: 2
optimizer:
  name: adam
  params:
    lr: 0.00020925014316361209
optimizer_name: adam
optimizer_params_lr: 0.00020925014316361209
path:
  data: /base_vol/sr_fca_main/experiments/inv_mnist/seed_9/data
  results: /base_vol/sr_fca_main/experiments/inv_mnist/seed_9/results/cfl
rounds: 53
seed: 9
stop_threshold: 0.44161910930492904
time:
  t0: 1665351727.8311546
  tcluster: 1665351839.8252683
  tdataset: 1665351728.300765
  tnew: 1665351728.300765
