model: 
  name: stacked_lstm
  params:
    seq_len : 80
    emb_dim: 8
    n_hidden: 256
    num_classes : 80
    n_layers: 2
freq:
  metrics: 40
  save: 150
  print: 40
num_clients_per_round: 10
local_iter: 400
rounds: 6
optimizer:
  name: sgd
  params:
    lr: 0.8



# choice with 25% test_acc
# optimizer:
#   name: sgd
#   params:
#     lr: 0.01
#     momentum: 0.9