client_threshold: 0.091239894625442
freq:
  metrics: 30
  print: 60
  save: 150
gamma_max: 0.1865467343604711
iterations: 250
local_iter: 5
model:
  name: two_layer_lin
  params:
    hidden_size: 200
    input_size: 784
    num_classes: 10
num_clients_per_round: 10
num_clusters: 4
optimizer:
  name: adam
  params:
    lr: 0.0009100199708881474
rounds: 50
stop_threshold: 0.9753536739327539
