client_threshold: 0.16597138279872914
freq:
  metrics: 30
  print: 60
  save: 150
gamma_max: 0.43203879744571816
iterations: 250
local_iter: 5
model:
  name: two_layer_lin
  params:
    hidden_size: 200
    input_size: 784
    num_classes: 10
num_clients_per_round: 10
num_clusters: 4
optimizer:
  name: adam
  params:
    lr: 0.0002
rounds: 50
stop_threshold: 0.0316441077433013
