freq:
  metrics: 30
  print: 60
  save: 30
iterations: 280
local_iter: 5
model:
  name: one_layer_lin
  params:
    dimension: 1000
    scale: 1
num_clients_per_round: 10
num_clusters: 2
optimizer:
  name: sgd
  params:
    lr: 0.00039092100715568237
optimizer_name: sgd
optimizer_params_lr: 0.00039092100715568237
rounds: 56
