model: 
  name: two_layer_lin
  params:
    input_size: 784
    hidden_size: 200
    num_classes: 10    
freq:
  metrics: 10
  save: 150
  print: 10
num_clients_per_round: 10
local_iter: 5
rounds: 50
iterations: 250
optimizer:
  name: adam
  params:
    lr: 0.0002
num_clusters: 4
