client_threshold: 0.015199140491065782
freq:
  metrics: 30
  print: 30
  save: 60
gamma_max: 0.6845659703911594
iterations: 280
local_iter: 5
model:
  name: one_layer_lin
  params:
    dimension: 1000
    scale: 1
num_clients_per_round: 10
num_clusters: 2
optimizer:
  name: sgd
  params:
    lr: 0.001
rounds: 56
stop_threshold: 0.675149972293246
