batch:
  test: 512
  train: 50
client_threshold: 4.4221798649162825
clustering: cfl
dataset:
  dimension: 1000
  name: synthetic
  noise_scale: 0.001
  num_clusters: 2
  num_samples:
    test: 100
    train: 100
  scale: 1
freq:
  metrics: 20
  print: 100
  save: 150
gamma_max: 0.4831359662887267
iterations: 280
local_iter: 3
model:
  name: one_layer_lin
  params:
    dimension: 1000
    scale: 1
num_clients: 50
num_clients_per_round: 8
num_clusters: 5
optimizer:
  name: sgd
  params:
    lr: 0.007802892291200698
    momentum: 0.16444238243159445
optimizer_name: sgd
optimizer_params_lr: 0.007802892291200698
optimizer_params_momentum: 0.16444238243159445
path:
  data: /base_vol/sr_fca_main/experiments/synthetic/seed_9/data
  results: /base_vol/sr_fca_main/experiments/synthetic/seed_9/results/cfl
rounds: 94
seed: 9
stop_threshold: 4.348561396247447
time:
  t0: 1665351137.4292896
  tcluster: 1665351148.3045762
  tdataset: 1665351137.8094316
  tnew: 1665351137.8094316
