stop_threshold: 0.01
gamma_max: 0.5
client_threshold: 4.4231
num_clusters: 2
rounds: 56
freq:
  metrics: 30
  print: 30
  save: 60
iterations: 280
local_iter: 5
model:
  name: one_layer_lin
  params:
    dimension: 1000
    scale: 1
num_clients_per_round: 10
optimizer:
  name: sgd
  params:
   lr : 0.001

