model: 
  name: one_layer_lin
num_clusters : 2
freq:
  metrics: 5
  save: 150
  print: 100
num_clients_per_round: 3
stop_threshold : 0.5
client_threshold : 0.6
gamma_max : 0.4
local_iter: 5
rounds: 60
optimizer:
  name: sgd
  params:
    lr: 0.1
