batch:
  test: 512
  train: 50
client_threshold: 17.718153249602942
clustering: cfl
dataset:
  dimension: 1000
  name: synthetic
  noise_scale: 0.001
  num_clusters: 2
  num_samples:
    test: 100
    train: 100
  scale: 1
dist_metric: euclidean
freq:
  metrics: 5
  print: 100
  save: 150
gamma_max: 0.20891218783422716
iterations: 300
local_iter: 2
model:
  name: one_layer_lin
  params:
    dimension: 1000
    scale: 1
num_clients: 50
num_clients_per_round: 9
num_clusters: 3
optimizer:
  name: sgd
  params:
    lr: 0.023498044698424203
    momentum: 0.3668740015202862
optimizer_name: sgd
optimizer_params_lr: 0.023498044698424203
optimizer_params_momentum: 0.3668740015202862
path:
  data: experiments/synthetic/seed_9/data
  results: experiments/synthetic/seed_9/results/cfl
rounds: 150
seed: 9
stop_threshold: 74.41236488510228
time:
  t0: 1664948799.3846555
  tdataset: 1664948799.8329701
  tnew: 1664948799.8329701
