model: 
  name: resnet
freq:
  metrics: 30
  save: 150
  print: 100
local_iter: 8
rounds: 250
optimizer:
  name: sgd
  params:
    lr: 0.5
    momentum: 0.9
    weight_decay :  0.0005
num_clients_per_round : 8
