model: 
  name: resnet
  num_classes: 10
freq:
  metrics: 10
  save: 150
  print: 10
local_iter: 5
rounds: 465
optimizer:
  name: sgd
  params:
    lr: 0.01
    momentum : 0.9
    weight_decay: 0.0005
num_clients_per_round : 10
label_smoothing: 0.1




# ffcv original
# model: 
#   name: resnet
#   num_classes: 10
# freq:
#   metrics: 30
#   save: 150
#   print: 100
# local_iter: 8
# rounds: 40
# optimizer:
#   name: sgd
#   params:
#     lr: 0.05
#     momentum: 0.9
#     weight_decay: 0.0005
# num_clients_per_round : 10
# label_smoothing: 0.1





