model: 
  name: stacked_lstm
  params:
    seq_len : 80
    emb_dim: 8
    n_hidden: 100
    num_classes : 80
    n_layers: 2
dist_threshold: 0.5
size_threshold: 1
freq:
  metrics: 5
  save: 150
  print: 100
num_refine_steps: 2
beta: 0.15
num_clients_per_round: 3
init:
  iterations: 10
refine:
  local_iter: 5
  rounds: 2
optimizer:
  name: sgd
  params:
    lr: 0.003
    momentum: 0.9
